baseurl = "https://lpdata.me/"
DefaultContentLanguage = "en"

paginate = 10

title = "Thoughtful Wanderings"
theme = "beautifulhugo"

metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

disqusShortname = ""
googleAnalytics = "UA-115577465-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = "Data thoughts with a Canadian perspective"
  logo = "img/tree_small.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = false
  useHLJS = true
  description = "Learning about R, data visualization and data science with a Canadian perspective."
  googlefonts = "https://fonts.googleapis.com/css?family=Lato|Lora"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Lawrence Pilch"
  website = "lpdata.com"
  email = "law9723@gmail.com"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
