---
title: Leaflet Map
author: Lawrence Pilch
date: '2018-05-22'
slug: leaflet-map
categories:
  - Toronto
  - Visualization
tags:
  - Toronto
  - Visualization
subtitle: ''
---

Here's a map  Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map Here's a map 

```{r, echo = FALSE, message = FALSE, warning = FALSE}

# Create neighbourhood map of toronto
# Colour 140 neighbourhoods according to B&E activity (2014-2017)
# 

library(tidyverse)
library(ggmap)
library(viridis)
library(sf)
library(tmap)
library(leaflet)
library(htmltools)

# Read toronto police crime data 2014 - 2017
df <- read_csv("/Users/law/Dropbox/R/to_crime/data/MCI_2014_to_2017.csv")
be <- filter(df, MCI == "Break and Enter")

# Read neighbourhood shapefile
hood_shp <- st_read("/Users/law/Dropbox/R/to_crime/data/neighbourhoods_wgs84/NEIGHBORHOODS_WGS84.shp", quiet = TRUE)

# Read neighbourhood population data
hood_pop <- read_csv("/Users/law/Dropbox/R/to_crime/data/hood_pop.csv") 

# Read street data. TO streets, rivers, walkways, boundaries, highways
rd <- st_read("/Users/law/Dropbox/R/to_crime/data/centreline_wgs84/CENTRELINE_WGS84.shp", quiet = TRUE) 
# Read park data
parks <-  st_read("/Users/law/Dropbox/R/to_crime/data/city_green_space_wgs84/CITY_GREEN_SPACE_WGS84.shp", quiet = TRUE)

# How many of each street type is there?
rd_desc <- rd %>% 
  group_by(FCODE_DESC) %>% 
  summarise(n = n())

# Remove geometry
rd_desc_df <- st_set_geometry(rd_desc, NULL)

# Look at highways
xway <- filter(rd_desc, FCODE_DESC == "Expressway")

# Look at major arterial
mart <- filter(rd_desc, FCODE_DESC == "Major Arterial")

# Add up number of B&Es in each neighbourhood
hood <- be %>% 
  group_by(Hood_ID) %>% 
  summarize(n = n())

# Add leading zeros to hood$Hood_ID, convert to factor to match hood_shp$AREA_S_CD which is a factor
# hood$Hood_ID <- sprintf("%03d", hood$Hood_ID)

# Prepare for merge by renaming neighbourhood column
hood_shp <- rename(hood_shp, Hood_ID = AREA_S_CD)

# Convert factors to integers
hood_shp$Hood_ID <- as.numeric(hood_shp$Hood_ID)

# Merge hood_shp (shapes) with hood based on Hood_ID (num B&Es per hood)
hood_shp <- hood_shp %>% 
  left_join(hood, by = "Hood_ID")

hood_shp <- rename(hood_shp, num_be = n)

# Merge hood_shp with hood pop'n
hood_shp <- hood_shp %>% 
  left_join(hood_pop, by = "Hood_ID")

# Add break and enter per capita per neighbourhood column
hood_shp <- mutate(hood_shp, be_per_cap = num_be / pop_2016)

# Add B&E per 1000 column
hood_shp <- mutate(hood_shp, density = be_per_cap * 1000)

# Remove geometry
hood_df <- st_set_geometry(hood_shp, NULL)

# # What CRS am I using?
# st_crs(hood_shp)

# Rank the neighbourhoods for B&E activity
# Need to use mutate to add column. If just assign hood_shp$rank <- NA it appears AFTER geometry which is bad.
hood_shp <- mutate(hood_shp, rank = NA)
hood_shp$rank <- rank(-hood_shp$density)

# Find mean B&E rate
be_avg <- mean(hood_shp$density)
hood_shp <- mutate(hood_shp, times_avg = round(density / be_avg, digits = 1))

# ------------------------------------------------------------------------------------------
# Interactive using Leaflet - multi-layer
#-------------------------------------------------------------------------------------------


# Text and formatting for mouseover
labels <- sprintf("<strong>%s</strong><br/>
                  Rank: %.0f, %.1fX Average",
                  hood_shp$Hood_Name, 
                  hood_shp$rank, 
                  hood_shp$times_avg
) %>% lapply(htmltools::HTML)

# Color scheme for neighbourhoods
pal <- colorBin("YlOrRd", domain = hood_shp$be_per_cap, bins = 8, pretty = TRUE)


# Add interactive map ---------------------------------------------------------------------
# -----------------------------------------------------------------------------------------
# Text and formatting for mouseover
labels <- sprintf("<strong>%s</strong><br/>
                  Rank: %.0f, %.1fX Average",
                  hood_shp$Hood_Name, 
                  hood_shp$rank, 
                  hood_shp$times_avg
) %>% lapply(htmltools::HTML)

# Color scheme for neighbourhoods
pal <- colorBin("YlOrRd", domain = hood_shp$be_per_cap, bins = 8, pretty = TRUE)

# Need to separate the borders from the fill since I need them on different layers
borders = hood_shp %>%
  st_cast("MULTILINESTRING")

# create a map with individual layer ordering using addMapPane
leaflet(options = leafletOptions(minZoom = 11, maxZoom = 14), width = "100%") %>%
  addTiles() %>%
  
  # Raster image surrounding Toronto
  addProviderTiles(providers$CartoDB.Positron) %>% 
  
  # Center map north of Toronto City Hall slightly zoomed in
  setView(lng = -79.384293, 
          lat = 43.685, #43.653908, 
          zoom = 12) %>% 
  
  addMapPane("hood_borders", zIndex = 430) %>%
  addMapPane("roads", zIndex = 425) %>% 
  addMapPane("parks", zIndex = 420) %>% 
  addMapPane("hoods", zIndex = 410) %>%
 
  # Add hood borders
  addPolylines(data = borders, 
               color = "white",
               opacity = 1, 
               weight = 2,
               options = pathOptions(pane = "hood_borders")) %>% 
 
  # Add highways
  addPolygons(data = xway,
              color = "sienna",
              weight = 1.0,
              opacity = 1.0,
              fillOpacity = 0.7,
              options = pathOptions(pane = "roads")) %>%

  # Add major arterial
  addPolygons(data = mart,
              color = "#737373",
              weight = 2.0,
              opacity = 0.5,
              fillOpacity = 1.0,
              options = pathOptions(pane = "roads")) %>%

  # Add parks
  addPolygons(data = parks,
              color = "green",
              weight = 1.0,
              opacity = 1.0,
              fillOpacity = 1.0,
              options = pathOptions(pane = "parks")) %>% 
  
  # Add hood fill
  addPolygons(data = hood_shp,
              fillColor = ~pal(be_per_cap),
              fillOpacity = 1.0,
              color = NA,
              options = pathOptions(pane = "hoods",
                                    
              # Highlight neighbourhoods upon mouseover
              highlight = highlightOptions(
                          color = "white",
                          weight = 4),
              
              # Add label info when mouseover
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto"))) %>% 
  
  # Add legend
  addLegend(data = hood_shp, 
            colors =c("#AA122E", "#F4AE7E", "#FEFDB7"),
            labels= c("More", "", "Less"),
            opacity = 1.0, 
            title = "B&Es",
            position = "bottomright")

